LastSessions<|||>1<|||>Unnamed
LastActiveSession<|||>1<|||>Unnamed
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
CreateDbCollation<|||>1<|||>utf8mb4_general_ci
MemoEditorWidth<|||>3<|||>136
ColWidths_frmTableEditor.listColumns<|||>1<|||>54,100,154,90,69,97,50,117,130,140,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>389,100,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>195,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,415
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
dbtreewidth<|||>3<|||>184
sqloutheight<|||>3<|||>115
FilterPanel<|||>3<|||>0
MainWinMaximized<|||>3<|||>0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,428
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,428,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,344
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,368
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
querymemoheight<|||>3<|||>282
MainWinLeft<|||>3<|||>70
MainWinTop<|||>3<|||>0
MainWinWidth<|||>3<|||>1054
MainWinHeight<|||>3<|||>735
DateTimeEditor_CursorPos_Type4<|||>3<|||>0
SessionManager_WindowLeft<|||>3<|||>323
SessionManager_WindowTop<|||>3<|||>189
ExportSQL_CreateDatabases<|||>3<|||>1
ExportSQL_CreateTables<|||>3<|||>1
ExportSQL_DataHow<|||>3<|||>3
ExportSQL_Filenames<|||>1<|||>C:\Users\alanv\Documents\LACAME\system_database.sql<{{{><}}}>
FileDialogEncoding_MainForm<|||>3<|||>0
SQLFile0<|||>1<|||>C:\Users\alanv\Documents\LACAME\system_database.sql
SQLFile1<|||>1<|||>C:\Users\alanv\AppData\Roaming\HeidiSQL\Backups\query-tab-2022-12-16_23-22-52-874.sql
SQLFile2<|||>1<|||>C:\Users\alanv\Documents\LACAME\api\create_tables.sql
Servers\Unnamed\SessionCreated<|||>1<|||>2022-10-28 15:37:01
Servers\Unnamed\Host<|||>1<|||>127.0.0.1
Servers\Unnamed\WindowsAuth<|||>3<|||>0
Servers\Unnamed\CleartextPluginEnabled<|||>3<|||>0
Servers\Unnamed\User<|||>1<|||>root
Servers\Unnamed\Password<|||>1<|||>5
Servers\Unnamed\LoginPrompt<|||>3<|||>0
Servers\Unnamed\Port<|||>1<|||>3306
Servers\Unnamed\NetType<|||>3<|||>0
Servers\Unnamed\Compressed<|||>3<|||>0
Servers\Unnamed\LocalTimeZone<|||>3<|||>0
Servers\Unnamed\QueryTimeout<|||>3<|||>30
Servers\Unnamed\KeepAlive<|||>3<|||>20
Servers\Unnamed\FullTableStatus<|||>3<|||>1
Servers\Unnamed\Databases<|||>1<|||>
Servers\Unnamed\Library<|||>1<|||>libmariadb.dll
Servers\Unnamed\Comment<|||>1<|||>
Servers\Unnamed\StartupScriptFilename<|||>1<|||>
Servers\Unnamed\TreeBackground<|||>3<|||>536870911
Servers\Unnamed\SSHtunnelHost<|||>1<|||>
Servers\Unnamed\SSHtunnelHostPort<|||>3<|||>22
Servers\Unnamed\SSHtunnelUser<|||>1<|||>
Servers\Unnamed\SSHtunnelPassword<|||>1<|||>5
Servers\Unnamed\SSHtunnelTimeout<|||>3<|||>4
Servers\Unnamed\SSHtunnelPrivateKey<|||>1<|||>
Servers\Unnamed\SSHtunnelPort<|||>3<|||>3307
Servers\Unnamed\SSL_Active<|||>3<|||>0
Servers\Unnamed\SSL_Key<|||>1<|||>
Servers\Unnamed\SSL_Cert<|||>1<|||>
Servers\Unnamed\SSL_CA<|||>1<|||>
Servers\Unnamed\SSL_Cipher<|||>1<|||>
Servers\Unnamed\IgnoreDatabasePattern<|||>1<|||>
Servers\Unnamed\LogFileDdl<|||>3<|||>0
Servers\Unnamed\LogFileDml<|||>3<|||>0
Servers\Unnamed\LogFilePath<|||>1<|||>C:\Users\alanv\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Unnamed\RefusedCount<|||>3<|||>10
Servers\Unnamed\ServerVersionFull<|||>1<|||>10.11.0-MariaDB - mariadb.org binary distribution
Servers\Unnamed\ConnectCount<|||>3<|||>34
Servers\Unnamed\ServerVersion<|||>3<|||>101100
Servers\Unnamed\LastConnect<|||>1<|||>2023-01-29 23:54:27
Servers\Unnamed\lastUsedDB<|||>1<|||>system_database
Servers\Unnamed\proto_teste|\MemoEditorHighlighter_user_id<|||>1<|||>
Servers\Unnamed\QueryHistory\1<|||>1<|||>2022-12-17 00:08:15|system_database|188|ALTER TABLE users AUTO_INCREMENT = 3;
Servers\Unnamed\QueryHistory\2<|||>1<|||>2023-01-14 13:20:26|system_database|2265|CREATE TABLE if NOT EXISTS Users(<{{{><}}}>	user_id	int AUTO_INCREMENT,<{{{><}}}>	user_name 	VARCHAR(70) NOT NULL,<{{{><}}}>	user_email	VARCHAR(320) UNIQUE NOT NULL,<{{{><}}}>	user_password	VARCHAR(64) NOT NULL,<{{{><}}}>	phone_number	VARCHAR(20) UNIQUE NOT NULL,<{{{><}}}>	adm_permission	BOOL NOT NULL DEFAULT false,<{{{><}}}>	last_login TIMESTAMP DEFAULT NULL,<{{{><}}}>	CONSTRAINT pk_user_id PRIMARY KEY(user_id)<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE if NOT EXISTS Projects(<{{{><}}}>	project_id int AUTO_INCREMENT,<{{{><}}}>	owner_id int NOT NULL,<{{{><}}}>	created_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP,<{{{><}}}>	end_in TIMESTAMP NOT NULL,<{{{><}}}>	project_name VARCHAR(50) NOT NULL,<{{{><}}}>	CONSTRAINT pk_project_id PRIMARY KEY(project_id),<{{{><}}}>	CONSTRAINT fk_projects_owner_id FOREIGN KEY (owner_id) REFERENCES Users(user_id) ON DELETE CASCADE<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE if NOT EXISTS ProjectUser(<{{{><}}}>	project_id int NOT NULL,<{{{><}}}>	user_id int NOT NULL,<{{{><}}}>	CONSTRAINT fk_projectuser_project_id FOREIGN KEY (project_id) REFERENCES Projects(project_id) ON DELETE CASCADE,<{{{><}}}>	CONSTRAINT fk_projectuser_user_id FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,<{{{><}}}>	CONSTRAINT pk_project_user PRIMARY KEY (project_id, user_id)<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE if NOT EXISTS Tasks(<{{{><}}}>	task_id int AUTO_INCREMENT,<{{{><}}}>	project_id int NOT NULL,<{{{><}}}>	owner_id int NOT NULL,<{{{><}}}>	begin_in TIMESTAMP NOT NULL,<{{{><}}}>	end_in TIMESTAMP NOT NULL,<{{{><}}}>	task_name VARCHAR(50) NOT NULL,<{{{><}}}>	task_description TEXT NOT NULL,<{{{><}}}>	task_status TINYINT(1) DEFAULT '0',<{{{><}}}>	CONSTRAINT pk_task_id PRIMARY KEY (task_id),<{{{><}}}>	CONSTRAINT fk_tasks_project_id FOREIGN KEY (project_id) REFERENCES Projects(project_id) ON DELETE CASCADE,<{{{><}}}>	CONSTRAINT fk_tasks_owner_id FOREIGN KEY (owner_id) REFERENCES Users(user_id) ON DELETE CASCADE<{{{><}}}>);<{{{><}}}><{{{><}}}>CREATE TABLE if NOT EXISTS Anexos(<{{{><}}}>	anexo_uuid VARCHAR(64) NOT NULL,<{{{><}}}>	task_id int NOT NULL,<{{{><}}}>	owner_id int NOT NULL,<{{{><}}}>	anexo_name VARCHAR(70) NOT NULL,<{{{><}}}>	anexo_description TEXT NOT NULL,<{{{><}}}>	file_extension VARCHAR(5) NOT NULL,<{{{><}}}>	created_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP,<{{{><}}}>	CONSTRAINT pk_anexo_uuid PRIMARY KEY (anexo_uuid),<{{{><}}}>	CONSTRAINT fk_anexos_task_id FOREIGN KEY (task_id) references Tasks(task_id) ON DELETE CASCADE,<{{{><}}}>	CONSTRAINT fk_anexos_owner_id FOREIGN KEY (owner_id) references Users(user_id) ON DELETE CASCADE<{{{><}}}>);
